apiVersion: v1
kind: Service
metadata:
  name: {{ include "phoebus-services-chart.fullname" . }}
  labels:
    {{- include "phoebus-services-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: sr-http
      protocol: TCP
      name: sr-http
  selector:
    {{- include "phoebus-services-chart.selectorLabels" . | nindent 4 }}
