apiVersion: v1
kind: Service
metadata:
  name: {{ include "phoebus-services-chart.fullname" . }}
  labels:
    {{- include "phoebus-services-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.staticIP }}
  clusterIP: {{.Values.staticIP}}
  {{- else }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rest
      protocol: TCP
      name: rest
    {{- if eq .Values.phoebusservice "olog" }}
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
    - port: 8181
      targetPort: ologrest
      protocol: TCP
      name: ologrest 
    {{- end }}
    # {{- if .Values.service.http.enable }}
    # - port: {{ .Values.service.http.port }}
    #   targetPort: http
    #   protocol: TCP
    #   name: http
    {{- end }}
  selector:
    {{- include "phoebus-services-chart.selectorLabels" . | nindent 4 }}
