apiVersion: v1
kind: Service
metadata:
  name: {{ include "phoebus-services-chart.fullname" . }}
  labels:
    {{- include "phoebus-services-chart.labels" . | nindent 4 }}
spec:

  type: {{ .Values.service.type }}
  {{- if .Values.staticIP }}
  clusterIP: {{ .Values.staticIP }}
  {{- else }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rest
      protocol: TCP
      name: rest
    {{- if .Values.service.http.enable }}
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "phoebus-services-chart.selectorLabels" . | nindent 4 }}
